### ISSUE TITLE
"Invalid" CSV with spaces after separators

### ISSUE THREAD

**Issue by greeny** [trafiklab/gtfs-php-sdk#3]
After parsing a lot of GTFS sources, I've found out some that have spaces after commas in files, for example this one from https://transitfeeds.com/p/metra/:
```
route_id, route_short_name, route_long_name, route_desc, agency_id, route_type, route_color, route_text_color, route_url
BNSF, BNSF, Burlington Northern, , METRA, 2, 29C233, 000000, https://metrarail.com/maps-schedules/train-lines/BNSF
HC, HC, Heritage Corridor, , METRA, 2, 550E0C, FFFFFF, https://metrarail.com/maps-schedules/train-lines/HC
MD-N, MD-N, Milwaukee North, , METRA, 2, CC5500, FFFFFF, https://metrarail.com/maps-schedules/train-lines/MD-N
MD-W, MD-W, Milwaukee West, , METRA, 2, F1AD0E, 000000, https://metrarail.com/maps-schedules/train-lines/MD-W
ME, ME, Metra Electric, , METRA, 2, EB5C00, FFFFFF, https://metrarail.com/maps-schedules/train-lines/ME
NCS, NCS, North Central Service, , METRA, 2, 9785BC, FFFFFF, https://metrarail.com/maps-schedules/train-lines/NCS
RI, RI, Rock Island, , METRA, 2, E02400, FFFFFF, https://metrarail.com/maps-schedules/train-lines/RI
SWS, SWS, Southwest Service, , METRA, 2, 0042A8, FFFFFF, https://metrarail.com/maps-schedules/train-lines/SWS
UP-N, UP-N, Union Pacific North, , METRA, 2, 008000, FFFFFF, https://metrarail.com/maps-schedules/train-lines/UP-N
UP-NW, UP-NW, Union Pacific Northwest, , METRA, 2, FFE600, 000000, https://metrarail.com/maps-schedules/train-lines/UP-NW
UP-W, UP-W, Union Pacific West, , METRA, 2, FE8D81, 000000, https://metrarail.com/maps-schedules/train-lines/UP-W
```

Now the obvious issue here is that it ges parsed and none of the values are assigned since the header row contains values with space at the begining.

I know this isn't really an issue of your library, but before I start making a PR, I basically wanted to ask if you think this is something that should be handled on library side. I have some suggestions on how to fix this:

1. `array_map('trim', $row)` for all rows. This will fix all issues related to extra spaces. However in a rare case where the space actually has to be in the name, this will strip it (but I can't imagine a case where space at the begining or end of anything will be required).
2. the same as above, but just for header row. That way data stays in the original form, but the header will be "fixed" in case it has spaces (and in header it's pretty much guaranteed that we won't have anything with required spaces)
3. some kind of "smart" detection of whether or not the spaces should be removed. I personally don't like this option, as it's a bit magical and the two above sound better to me.

If you think that one of these should be implemented, let me know and I'll prepare a PR.

Thanks!

**Comment by Bertware** [comment]
According to the GTFS specification, there shouldn't be any leading or trailing spaces. This could also cause issues when trying to determine whether a value is present.

From "File Requirements" on https://gtfs.org/reference/static :
> Remove any extra spaces between fields or field names. Many parsers consider the spaces to be part of the value, which may cause errors.

The first option of running array_map on all rows sounds good to me, feel free to go ahead and create a PR.
